---
- name: Windows Inventory CSV and Push to GitHub
  hosts: all
  gather_facts: yes

  vars:
    csv_file: windows_inventory.csv

  tasks:
    - name: Build CSV line
      set_fact:
        csv_line: >-
          {{ ansible_hostname }},
          {{ ansible_facts.os_name }},
          {{ ansible_facts.os_version }},
          {{ ansible_facts.os_build }}

    - name: Create CSV header (once)
      copy:
        dest: "{{ playbook_dir }}/{{ csv_file }}"
        content: "hostname,os_name,os_version,os_build\n"
      run_once: true
      delegate_to: localhost

    - name: Append CSV data
      lineinfile:
        path: "{{ playbook_dir }}/{{ csv_file }}"
        line: "{{ csv_line }}"
      delegate_to: localhost

- name: Commit and Push CSV to GitHub
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Git add
      command: git add windows_inventory.csv
      args:
        chdir: "{{ playbook_dir }}"

    - name: Git commit
      command: git commit -m "Update Windows inventory CSV"
      args:
        chdir: "{{ playbook_dir }}"
      ignore_errors: yes

    - name: Git push
      command: git push
      args:
        chdir: "{{ playbook_dir }}"
