---
- name: Windows Inventory CSV (Artifacts)
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect system info
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        $cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
        $mem = Get-CimInstance Win32_ComputerSystem
        "$env:COMPUTERNAME,$($os.Caption),$($cpu.Name),$([math]::Round($mem.TotalPhysicalMemory/1GB,2))"
      register: sysinfo

    - name: Build CSV content
      delegate_to: localhost
      run_once: true
      copy:
        dest: /runner/project/windows_inventory.csv
        content: |
          Hostname,OS,CPU,MemoryGB
          {% for host in ansible_play_hosts_all %}
          {{ hostvars[host].sysinfo.stdout }}
          {% endfor %}

    - name: Publish CSV as AWX Artifact
      set_stats:
        data:
          windows_inventory_csv: "/runner/project/windows_inventory.csv"
