---
- name: Windows Inventory CSV (AWX Artifacts)
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect OS info
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        "$($env:COMPUTERNAME),$($os.Caption),$($os.Version)"
      register: osinfo

    - name: Build CSV content
      set_fact:
        csv_data: |
          hostname,os,version
          {% for h in ansible_play_hosts %}
          {{ hostvars[h].osinfo.stdout }}
          {% endfor %}

    - name: Publish CSV as AWX artifact
      set_stats:
        data:
          windows_inventory_csv: "{{ csv_data }}"
        aggregate: true
