---
- name: Collect Windows inventory and generate CSV
  hosts: all
  gather_facts: yes

  vars:
    project_dir: /var/lib/awx/projects/windows-manual-project
    report_file: windows_inventory_report.csv

  tasks:
    - name: Create CSV header (run once)
      copy:
        dest: "{{ project_dir }}/{{ report_file }}"
        content: "Hostname,IP,OS,OS_Version,CPU_Count,Total_Memory_MB,Ping_Status\n"
      run_once: true
      delegate_to: localhost

    - name: Append server details to CSV
      lineinfile:
        path: "{{ project_dir }}/{{ report_file }}"
        line: >-
          {{ ansible_hostname }},
          {{ ansible_default_ipv4.address }},
          {{ ansible_os_name }},
          {{ ansible_os_version }},
          {{ ansible_processor_count }},
          {{ (ansible_memtotal_mb | default('NA')) }},
          SUCCESS
        insertafter: EOF
      delegate_to: localhost

- name: Commit and push CSV report to GitHub
  hosts: localhost
  gather_facts: no

  vars:
    project_dir: /var/lib/awx/projects/windows-manual-project
    report_file: windows_inventory_report.csv

  tasks:
    - name: Git add CSV
      shell: git add {{ report_file }}
      args:
        chdir: "{{ project_dir }}"

    - name: Git commit CSV
      shell: git commit -m "Update Windows inventory report"
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: yes

    - name: Git push CSV
      shell: git push origin main
      args:
        chdir: "{{ project_dir }}"
