---
# PART 1: Collect data from Windows servers
- name: Collect Windows inventory
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect Windows OS details
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        "$($env:COMPUTERNAME),$($os.Caption),$($os.Version),$($os.BuildNumber)"
      register: win_os

    - name: Save CSV line per host
      set_fact:
        csv_line: "{{ win_os.stdout }}"

# PART 2: Build CSV and push to GitHub (controller only)
- name: Build CSV and push to GitHub
  hosts: localhost
  gather_facts: no

  vars:
    csv_file: windows_inventory.csv

  tasks:
    - name: Create CSV header
      copy:
        dest: "/runner/project/{{ csv_file }}"
        content: "hostname,os_name,os_version,os_build\n"

    - name: Append Windows data
      lineinfile:
        path: "/runner/project/{{ csv_file }}"
        line: "{{ hostvars[item].csv_line }}"
        insertafter: EOF
      loop: "{{ groups['windows'] }}"

    - name: Git add
      command: git add {{ csv_file }}
      args:
        chdir: /runner/project

    - name: Git commit
      command: git commit -m "Update Windows inventory CSV"
      args:
        chdir: /runner/project
      ignore_errors: yes

    - name: Git push
      command: git push origin main
      args:
        chdir: /runner/project
