---
- name: Windows Inventory CSV (AWX Artifact)
  hosts: all
  gather_facts: no
  tasks:
    - name: Collect OS info
      win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        "$($env:COMPUTERNAME),$($os.Caption),$($os.Version),$($os.BuildNumber)"
      register: win_os

    - name: Save CSV line
      set_fact:
        csv_line: "{{ inventory_hostname }},{{ win_os.stdout_lines[0] }}"

- name: Publish CSV as AWX artifact
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build CSV content
      set_fact:
        csv_content: |
          ip,hostname,os,version,build
          {% for h in groups['all'] %}
          {{ hostvars[h].csv_line }}
          {% endfor %}

    - name: Publish artifact
      set_stats:
        data:
          windows_inventory_csv: "{{ csv_content }}"
